# Generated by Django 5.1.2 on 2025-02-27 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('author', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('genre', models.CharField(blank=True, choices=[('documentary', 'documentary'), ('action', 'action'), ('horror', 'horror'), ('drama', 'drama'), ('romance', 'romance')], db_index=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, choices=[('french', 'french'), ('english', 'english'), ('german', 'german')], max_length=150, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('poster', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('video_file_hd360', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('video_file_hd480', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('video_file_hd720', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('video_file_hd1080', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
