# Generated by Django 5.1.2 on 2025-02-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vtt_file',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
