# Generated by Django 5.1.2 on 2025-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_video_created_by_video_is_favorite_video_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('documentary', 'documentary'), ('action', 'action'), ('horror', 'horror')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
