# Generated by Django 5.1.2 on 2025-03-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_video_vtt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, choices=[('documentary', 'documentary'), ('action', 'action'), ('horror', 'horror'), ('drama', 'drama'), ('technic', 'technic')], db_index=True, max_length=100, null=True),
        ),
    ]
