# Generated by Django 5.1.2 on 2025-02-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0005_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='created_by',
            new_name='uploaded_by',
        ),
    ]
