# Generated by Django 5.1.2 on 2025-02-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0007_alter_video_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
