# Generated by Django 5.1.2 on 2025-02-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0008_alter_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='genre',
        ),
    ]
