# Generated by Django 5.1.2 on 2025-02-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0009_rename_category_video_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_hd1080',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_hd360',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_hd480',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_hd720',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, choices=[('documentary', 'documentary'), ('action', 'action'), ('horror', 'horror'), ('drama', 'drama'), ('romance', 'romance')], db_index=True, max_length=100, null=True),
        ),
    ]
