"""
Django settings for videoflix project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from config.config_settings import *
from configurations import Configuration, values



class Dev(Configuration):
            
        # Build paths inside the project like this: BASE_DIR / 'subdir'.
        BASE_DIR = Path(__file__).resolve().parent.parent


        # Quick-start development settings - unsuitable for production
        # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

        # SECURITY WARNING: keep the secret key used in production secret!
        SECRET_KEY = 'django-insecure-#ur8mrc$*jv0#*jlr5pu$49!s9(io^v8y4q8oq__ovg0doe=2='

        # SECURITY WARNING: don't run with debug turned on in production!
        DEBUG = True

        ALLOWED_HOSTS = [
                'localhost',
                '127.0.0.1',
        ]


        # Application definition

        INSTALLED_APPS = [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'corsheaders',
            'rest_framework',
            'rest_framework.authtoken',
            'authentication.apps.AuthenticationConfig',
            'debug_toolbar',
            'django_filters',
            'user',
            'django_rq',
            'import_export',
            'videoflix_app.apps.VideoflixAppConfig',

        ]

        AUTH_USER_MODEL = 'user.CustomUser'


        RQ_QUEUES = {
            'default': {
                'HOST': 'localhost',
                'URL': f'redis://:{RQ_PWD}@127.0.0.1:6379/1',
                'PORT': 6379,
                'DB': 0,
                "password":RQ_PWD,
                'DEFAULT_TIMEOUT': 360,
            
            },

        
        }

        CACHE_TTL = 60 * 15 # cache every 15 minutes

        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": f"redis://:{RQ_PWD}@127.0.0.1:6379/1",
                "OPTIONS":{
                    "password":RQ_PWD,
                },
                "KEY_PREFIX":"videoflix_app",
            }
        }


        MIDDLEWARE = [
            'debug_toolbar.middleware.DebugToolbarMiddleware',
            'django.middleware.security.SecurityMiddleware',
            'corsheaders.middleware.CorsMiddleware',
            'django.contrib.sessions.middleware.SessionMiddleware',
            'django.middleware.common.CommonMiddleware',
            'django.middleware.csrf.CsrfViewMiddleware',
            'django.contrib.auth.middleware.AuthenticationMiddleware',
            'django.contrib.messages.middleware.MessageMiddleware',
            'django.middleware.clickjacking.XFrameOptionsMiddleware',
        ]

        INTERNAL_IPS = [
            '127.0.0.1',
        ]

        ROOT_URLCONF = 'videoflix.urls'


        CORS_ALLOWED_ORIGINS = [
        "https://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:4200"
        ]

        CORS_ALLOW_HEADERS = [
            'authorization',
            'content-type',
        ]

        TEMPLATES = [
            {
                'BACKEND': 'django.template.backends.django.DjangoTemplates',
                'DIRS': [BASE_DIR / "authentication/templates"],
                'APP_DIRS': True,
                'OPTIONS': {
                    'context_processors': [
                        'django.template.context_processors.debug',
                        'django.template.context_processors.request',
                        'django.contrib.auth.context_processors.auth',
                        'django.contrib.messages.context_processors.messages',
                    ],
                },
            },
        ]

        WSGI_APPLICATION = 'videoflix.wsgi.application'


        # Database
        # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'USER': SQL_USER,
                'PASSWORD': SQL_PWD,
                'NAME': DB_NAME,
                'HOST':DB_HOST,
                'PORT':5432,
            }
        }


        # Password validation
        # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

        AUTH_PASSWORD_VALIDATORS = [
            {
                'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
            },
            {
                'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
                'OPTIONS': {'min_length': 8},
            },
            {
                'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
            },
            {
                'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
            },
        ]


        # Internationalization
        # https://docs.djangoproject.com/en/5.1/topics/i18n/

        LANGUAGE_CODE = 'en-us'

        TIME_ZONE = 'UTC'

        USE_I18N = True

        USE_TZ = True


        # Static files (CSS, JavaScript, Images)
        # https://docs.djangoproject.com/en/5.1/howto/static-files/

        STATIC_URL = '/static/'
        STATIC_ROOT = os.path.join(BASE_DIR, 'static')

        STATICFILES_DIRS = [
            os.path.join(BASE_DIR, 'authentication/static'),
        ]

        IMPORT_EXPORT_USE_TRANSACTIONS = True



        MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
        MEDIA_URL = '/media/'


        # Default primary key field type
        # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

        DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

        EMAIL_BACKEND = EMAIL_BACKEND
        EMAIL_HOST = EMAIL_HOST
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_HOST_USER = MAIL_USERNAME  
        EMAIL_HOST_PASSWORD = MAIL_PASSWORD



        REST_FRAMEWORK = {
        
            'DEFAULT_AUTHENTICATION_CLASSES': [
                'rest_framework.authentication.TokenAuthentication',
                'rest_framework.authentication.SessionAuthentication',
            ],
            'DEFAULT_FILTER_BACKENDS': [
                'django_filters.rest_framework.DjangoFilterBackend',
                'rest_framework.filters.OrderingFilter',
                'rest_framework.filters.SearchFilter',
            ],
        'DEFAULT_THROTTLE_CLASSES': [
                'rest_framework.throttling.AnonRateThrottle',
                'rest_framework.throttling.UserRateThrottle'
        ],
            'DEFAULT_THROTTLE_RATES':{
                'anon':'50/minute',
                'user':'80/minute',
                'eighty':'80/second',
            },
            }
        


class Prod(Dev):
        DEBUG = False
        SECRET_KEY = values.SecretValue()